version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.21
    commands:
      - go mod tidy

  build:
    commands:
      - GOOS=linux GOARCH=amd64 go build -o main
      - zip function.zip main

  post_build:
    commands:
      - aws lambda update-function-code --function-name SrihariEmployeeFetcherLambda --zip-file fileb://function.zip --region us-west-2
